### PR TITLE
CNKAF-1140: Default to confluent.balancer.enable=true

### PR DESCRIPTION
**Pull request by stanislavkozlovski**

### CODE REVIEW

**Comment by stanislavkozlovski** [comment]
This patch is has not yet been tested

**Comment by stanislavkozlovski** [comment]
Build failing with:

```
08:12:14  Error response from daemon: conflict: unable to delete 49969870cd23 (cannot be forced) - image has dependent child images
[Pipeline] sh
08:12:14  No images for 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-kafka-connect-base need cleanup
[Pipeline] sh
08:12:14  No images for 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-kafka-connect need cleanup
[Pipeline] sh
08:12:14  No images for 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-server-connect-base need cleanup
[Pipeline] sh
08:12:15  No images for 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-server-connect need cleanup
[Pipeline] }
[Pipeline] // withDockerServer
```

----------------------------------------------------------------------
This change has been tested by manually running `cp-demo` and overriding its docker compose yml to set the KAFKA_CONFLUENT_BALANCER_ENABLE env variable to true.
```
[2020-08-31 07:57:43,905] INFO Starting Kafka Cruise Control... (com.linkedin.kafka.cruisecontrol.KafkaCruiseControl)
[2020-08-31 07:57:44,410] INFO Kafka Cruise Control started. (com.linkedin.kafka.cruisecontrol.KafkaCruiseControl)
```

@sdanduConf further verified it works by enabling the rest proxy and seeing SBK come up on C3.
He also verified that the lack of the variable results in `confluent.balancer.enable=false` through manual edits in the `cp-all-in-one` repo

**Comment by stanislavkozlovski** [comment]
Retargeted to 6.0.x

**Comment by sdanduConf** [comment]
mistakenly ran an extra pr build, previous build passed - https://jenkins.confluent.io/job/confluentinc-pr/job/kafka-images/view/change-requests/job/PR-55/6/

**Pull request merged**
