### PR TITLE
Add support for balancer configs

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
There are configs like this under `server/`, `kafka/`, and `ce-kafka`. I think they probably don't need to be whitelisted in `kafka/`, but not sure what the difference between `server/` and `ce-kafka/` are, so not sure how many places this needs copy/paste.

**Comment by xli1996** [comment]
I think what they want is configs in `server.properties`, do we also set configs in `server.properties` it in `kafka.properties.template` as well?

**Comment by mingfang** [comment]
we also need to be able to set configs in `server.properties` for tier storage.

**Comment by cchristous** [comment]
This PR is very old. Closing to get it off the list. Feel free to re-open.

**Pull request closed without merging**
