### PR TITLE
MINOR: Remove GCS connector in 6.0 and newer

### PR DESCRIPTION
**Pull request by kkonstantine**
Aims to resolve https://confluentinc.atlassian.net/browse/CC-9907

### CODE REVIEW

**Comment by kkonstantine** [comment]
This PR is to remove GCS and resolve a couple of blockers for CP 6.0 that were created after CVE scanning. 

There is a more general question on whether we should remove this image altogether (I think we should). 
But there might be some considerations around naming or other aspects. 

Lmk what you think and I can either merge here and issue a follow up PR, or remove this image and keep only `kafka-connect-base` in this PR as well.

**Comment by andrewegel** [comment]
> There is a more general question on whether we should remove this image altogether (I think we should).

My vote is to just remove the images then - They're effectively empty after this change and no longer serve any value.

As long as theres documentation & communication (to customers & the rest of confluent) to back up this aspect up, I'm fine with removing the image.

I'm not sure who else makes these sorts of calls, maybe @addisonhuddy should be an Approver on this change?

**Comment by kkonstantine** [comment]
A quick search on our github org shows that the removal of `cp-kafka-connect` would influence 
a) demos (should adapt to the absence of connectors anyways) 
b) some training material
c) a few replicator tests such as: [test_enterprise_replicator.py](https://github.com/confluentinc/kafka-replicator-images/blob/9b2844097e50b25760a13747909c4ed3700ac029/replicator/test/test_enterprise_replicator.py#L47)
d) some docker based connector tests
e) [cp-helm-chars](https://github.com/confluentinc/cp-helm-charts/blob/15e3b730476a798351c98c977329ba97044ca46e/charts/cp-kafka-connect/values.yaml)
f) [docs](https://github.com/confluentinc/cp-helm-charts/blob/15e3b730476a798351c98c977329ba97044ca46e/charts/cp-kafka-connect/values.yaml)

Removing `confluentinc/cp-server-connect` would have a much smaller impact on demos, training material and a few replicator fault injection tests. 

Replicator images are based off of the base connect images so I don't see a problem there. 

The easiest way would be to merge here and notify owners of the above to replace refs to `cp-kafka-connect` with `cp-kafka-connect-base` and test. 

Lmk what you think
cc @NathanNam

**Comment by kkonstantine** [comment]
Created https://confluentinc.atlassian.net/browse/CC-10812 to track future removal of duplicate images. 
Merging to fix CVEs.

**Pull request merged**
